In [48]:
import numpy as np
import pandas as pd
pd.set_option("display.max_columns",None)

In [49]:
df = pd.read_csv(r'E:\DESKTOP\mlops\app\datasets\train.csv')

In [50]:
df.head()

,id,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Admission grade,Displaced,Educational special needs,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,International,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,0,1,1,1,9238,1,1,126.0,1,1,19,5,5,122.6,0,0,0,1,0,1,18,0,0,6,6,6,14.500000,0,0,6,7,6,12.428571,0,11.1,0.6,2.02,Graduate
1,1,1,17,1,9238,1,1,125.0,1,19,19,9,9,119.8,1,0,0,1,0,0,18,0,0,6,8,4,11.600000,0,0,6,9,0,0.000000,0,11.1,0.6,2.02,Dropout
2,2,1,17,2,9254,1,1,137.0,1,3,19,2,3,144.7,0,0,0,1,1,0,18,0,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,16.2,0.3,-0.92,Dropout
3,3,1,1,3,9500,1,1,131.0,1,19,3,3,2,126.1,1,0,0,1,0,1,18,0,0,7,9,7,12.591250,0,0,8,11,7,12.820000,0,11.1,0.6,2.02,Enrolled
4,4,1,1,2,9500,1,1,132.0,1,19,37,4,9,120.1,1,0,0,1,0,0,18,0,0,7,12,6,12.933333,0,0,7,12,6,12.933333,0,7.6,2.6,0.32,Graduate

In [51]:
df = df.iloc[:15000,:]

In [52]:
df_cols = df.columns
df_cols

Index(['id', 'Marital status', 'Application mode', 'Application order',
       'Course', 'Daytime/evening attendance', 'Previous qualification',
       'Previous qualification (grade)', 'Nacionality',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Admission grade',
       'Displaced', 'Educational special needs', 'Debtor',
       'Tuition fees up to date', 'Gender', 'Scholarship holder',
       'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)', 'Unemployment rate',
       'Inflation rate', 'GDP', 'Target'],
      dtype='object')

In [53]:
X = df[['Daytime/evening attendance','Previous qualification (grade)']]

y = df[['Target']]

In [54]:
X.head()

   Daytime/evening attendance  Previous qualification (grade)
0                           1                           126.0
1                           1                           125.0
2                           1                           137.0
3                           1                           131.0
4                           1                           132.0

In [55]:
set(y.Target)

{'Dropout', 'Enrolled', 'Graduate'}

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=63,test_size=0.15)

In [57]:
#from sklearn.preprocessing import MinMaxScaler

#scale = MinMaxScaler()
#X_train = scale.fit_transform(X_train)
#X_test = scale.transform(X_test)

In [58]:
y = pd.get_dummies(y,columns = ['Target']).replace({True:1.0, False:0.0})

C:\Users\dg725\AppData\Local\Temp\ipykernel_10336\49490933.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = pd.get_dummies(y,columns = ['Target']).replace({True:1.0, False:0.0})

In [59]:
y

       Target_Dropout  Target_Enrolled  Target_Graduate
0                 0.0              0.0              1.0
1                 1.0              0.0              0.0
2                 1.0              0.0              0.0
3                 0.0              1.0              0.0
4                 0.0              0.0              1.0
...               ...              ...              ...
14995             0.0              0.0              1.0
14996             0.0              0.0              1.0
14997             0.0              0.0              1.0
14998             0.0              0.0              1.0
14999             0.0              0.0              1.0

[15000 rows x 3 columns]

In [60]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

classifier = RandomForestClassifier(n_estimators=80,max_depth=10,criterion='entropy')

model = classifier.fit(X_train, y_train)

print(accuracy_score(y_test,model.predict(X_test))*100)

c:\Users\dg725\.conda\envs\dhoni\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

55.06666666666666

In [64]:
X_test.iloc[66:67,:]

      Daytime/evening attendance  Previous qualification (grade)
7380                           1                           138.0

In [47]:
import joblib
# Save the model
joblib.dump(model, 'model.joblib')
# Load the model
#loaded_model = joblib.load('model.joblib')

['model.joblib']